CREATE TABLE "ATG_3716_Comp_Ship"(
 "ORDER_NO" CHAR(7),
 "ORDER_SUFFIX" CHAR(4),
 "ORDER_REC" CHAR(4),
 "CUSTOMER" CHAR(6),
 "PART" CHAR(20),
 "CUSTOMER_PO" CHAR(15),
 "SHIP_VIA" CHAR(20),
 "DATE_DUE" DATE,
 "QTY_SCHED" NUMERIC(13,4),
 "WAY_BILL" CHAR(19),
 "PHY_SHIP" DATE,
 "COMM" LONGVARCHAR
);